### ISSUE TITLE
Support Node.JS v5.0.0

### ISSUE THREAD

**Issue by buinskii** [moll/node-syslogh#3]
I have next error, when I trying require('syslogh') on node.js v5.0.0

Error: Could not locate the bindings file. Tried:
→ _/node_modules/syslogh/build/index.node
→ */node_modules/syslogh/build/Debug/index.node
→ */node_modules/syslogh/build/Release/index.node
→ */node_modules/syslogh/out/Debug/index.node
→ */node_modules/syslogh/Debug/index.node
→ */node_modules/syslogh/out/Release/index.node
→ */node_modules/syslogh/Release/index.node
→ */node_modules/syslogh/build/default/index.node
→ */node_modules/syslogh/compiled/5.0.0/linux/x64/index.node
at bindings (_/node_modules/bindings/bindings.js:88:9)
at Object.<anonymous> (*/node_modules/syslogh/index.js:3:47)
at Module._compile (module.js:425:26)
at Object.Module._extensions..js (module.js:432:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:311:12)
at Module.require (module.js:366:17)
at require (module.js:385:17)
at new Syslog (/home/buinskii/www/noddy/lib/logger/transports/syslog.js:15:23)
at Logger.<anonymous> (/home/buinskii/www/noddy/lib/logger/logger.js:91:33)

**Comment by moll** [comment]
Hey! I haven't yet given it a try on Node v5, but I'd presume it would have compile errors, rather than `require` related errors. If you installed Syslogh, did it compile properly?

**Comment by moll** [comment]
You can force it to recompile (which it should do on installation unless you've used `--ignore-scripts true`) with:

```
npm --ignore-scripts false rebuild --build-from-source syslogh
```

**Comment by buinskii** [comment]
Thank you! If I run:
`npm --ignore-scripts false rebuild --build-from-source syslogh`
the module builds correctly and works good

I think, when I try `npm install syslogh` module doesn`t compile automatically.
A see next output: 
$ npm install syslogh
npm WARN engine syslogh@1.2.1: wanted: {"node":">= 0.10.28 < 0.11 || >= 0.11.15 < 5"} (current: {"node":"5.0.0","npm":"3.3.6"})
mymodule@3.0.0 /mymoduledir
└── syslogh@1.2.1

**Comment by moll** [comment]
Do you have any lines mentioning `user-scripts` in your `.npmrc`? That's not a bad thing to _not_ run random code when you install, but it does have the limitation you need to rebulid stuff manually for those modules that do need it. ;-)

**Comment by buinskii** [comment]
No, I haven't. When I try `npm install syslogh` on Node.JS v4.0.0 module compile automatically)

**Comment by buinskii** [comment]
When I try `npm install https://github.com/moll/node-syslogh`
module compile automatically and work fine) It`s very strange for me =(

**Comment by moll** [comment]
Ah, perhaps Node v5 with its NPM changed something about getting it to autocompile. I'll have to see.
What NPM version are you on?

**Comment by buinskii** [comment]
It`s 3.3.6
